# Generated by Django 5.1.6 on 2025-02-25 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='logistics.container'),
        ),
        migrations.AddField(
            model_name='car',
            name='procedure',
            field=models.CharField(choices=[('transit', 'Транзит'), ('reexport', 'Реекспорт'), ('import', 'Импорт'), ('export', 'Экспорт')], default='transit', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='title',
            field=models.CharField(choices=[('ours', 'У нас'), ('warehouse', 'У склада'), ('delivered', 'Передан клиенту'), ('waiting_from_usa', 'Ждем из USA')], default='ours', max_length=20),
        ),
    ]
