# Generated by Django 5.1.6 on 2025-02-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_rename_amount_payment_amount_due_payment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_stored',
            field=models.DateField(blank=True, null=True),
        ),
    ]
