# Generated by Django 5.1.6 on 2025-02-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_rename_amount_payment_amount_due_car_date_stored_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='days_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='DAYS'),
        ),
        migrations.AddField(
            model_name='car',
            name='prof',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='PROF'),
        ),
        migrations.AddField(
            model_name='car',
            name='sklad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='SKLAD'),
        ),
        migrations.AddField(
            model_name='car',
            name='ths',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='THS'),
        ),
        migrations.AddField(
            model_name='car',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='TOTAL'),
        ),
    ]
