# Generated by Django 5.1.6 on 2025-02-28 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_car_days_cost_car_prof_car_sklad_car_ths_car_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.warehouse', verbose_name='Склад'),
        ),
    ]
