# Generated by Django 5.1.6 on 2025-02-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_car_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='logistics.car'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
