# Generated by Django 5.1.6 on 2025-02-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_invoice_cars_alter_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='ths',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='THS'),
        ),
    ]
