# Generated by Django 5.1.6 on 2025-02-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_container_ths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(choices=[('ours', 'У нас'), ('warehouse', 'У склада'), ('delivered', 'Передан клиенту'), ('waiting_from_usa', 'USA')], default='ours', max_length=20),
        ),
    ]
