# Generated by Django 5.1.6 on 2025-02-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_alter_car_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('mutual_settlement', 'Взаимозачёт')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(choices=[('ours', 'У нас'), ('warehouse', 'У склада'), ('delivered', 'Передан клиенту'), ('waiting_from_usa', 'Ждем из USA')], default='ours', max_length=20),
        ),
    ]
